version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gamevault-db
    environment:
      MYSQL_ROOT_PASSWORD: Sandia4you
      MYSQL_DATABASE: game_vault
      MYSQL_USER: user
      MYSQL_PASSWORD: contraseña
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql